// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (user_id, created_at, content)
VALUES ($1, NOW(), $2)
RETURNING id, created_at, user_id, content
`

type CreateMessageParams struct {
	UserID  uuid.UUID
	Content string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.UserID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.Content,
	)
	return i, err
}

const getRecentMessages = `-- name: GetRecentMessages :many
SELECT m.id, m.created_at, m.user_id, m.content, u.username
FROM messages m
JOIN users u ON m.user_id = u.id
ORDER BY m.created_at DESC
LIMIT $1
`

type GetRecentMessagesRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UserID    uuid.UUID
	Content   string
	Username  string
}

func (q *Queries) GetRecentMessages(ctx context.Context, limit int32) ([]GetRecentMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentMessagesRow
	for rows.Next() {
		var i GetRecentMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.Content,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
